# Default SAC parameters for OpenAI Gym MuJoCo tasks

args: 
  update_every_n_steps: 1
  n_random_actions: 10000
  n_collect_steps: 1000

alg_config:
  action_lim: 1
  lr: 3.e-4
  gamma: 0.99
  tau: 5.e-3
  batch_size: 256
  hidden_size: 256
  update_interval: 1
  buffer_size: 1.e+6
  # If this is None, it will default to -dim(A) as per SAC Applications paper
  target_entropy: null