# Default TD3 parameters for OpenAI Gym MuJoCo tasks

args: 
  update_every_n_steps: 1
  n_random_actions: 25000
  n_collect_steps: 1000

alg_config:
  lr: 3e-4
  gamma: 0.99
  tau: 5e-3
  batch_size: 256
  hidden_size: 256
  update_interval: 2
  buffer_size: 1e6
  target_noise: 0.2
  target_noise_clip: 0.5
  explore_noise: 0.1